version: "2"
services:
  frontend:
    image: node:10.9-stretch
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
      - HOST=frontend
    volumes:
      - ../lintol-frontend:/home/node/app
    ports:
      - "8080:8080"
    command: "npm start"
  db:
    image: postgres
    volumes:
      - ./docker/storage/db:/data
    environment:
      PGDATA: /data
    env_file:
      - ./docker/config/laravel.env
  phpfpm:
    #image: test_artisan_worker:latest
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/data/www
      - .:/var/www/app
      - ./docker/storage/phpfpm/xdebug:/tmp/xdebug
    env_file:
      - ./docker/config/laravel.env
      - ./docker/config/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      APP_LOG: "errorlog"
      LOG_CHANNEL: "errorlog"
  nginx:
    image: nginx:stable
    volumes:
      - ./infrastructure/containers/nginx/laravel-dev:/etc/nginx/conf.d/default.conf
      - ./docker/certificates:/secrets
      - .:/var/www/app
    env_file:
      - ./docker/config/laravel.env
    ports:
      - "8000:80"
    links:
      - phpfpm:phpfpm
    environment:
      LARAVEL_ROOT: "/var/www/app"
  artisan_new_resources_subscriber:
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    volumes:
      - .:/var/www/app
    env_file:
      - ./docker/config/laravel.env
      - ./docker/config/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      APP_LOG: "errorlog"
      LOG_CHANNEL: "errorlog"
    links:
      - db:db
      - redis:redis
    entrypoint:
      - php
      - /var/www/app/artisan
    command:
      - "ltl:observe-new"
  artisan_subscriber:
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    volumes:
      - .:/var/www/app
    env_file:
      - ./docker/config/laravel.env
      - ./docker/config/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      APP_LOG: "errorlog"
      LOG_CHANNEL: "errorlog"
    links:
      - db:db
      - redis:redis
    entrypoint:
      - php
      - /var/www/app/artisan
    command:
      - "ltl:observe"
  artisan_worker:
    build:
      context: ./infrastructure/containers/phpfpm
      dockerfile: Dockerfile.debug
    volumes:
      - .:/var/www/app
    env_file:
      - ./docker/config/laravel.env
      - ./docker/config/redis.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      APP_LOG: "errorlog"
      LOG_CHANNEL: "errorlog"
    links:
      - db:db
      - redis:redis
    entrypoint:
      - php
      - /var/www/app/artisan
    command:
      - "queue:work"
  redis:
    image: redis
    env_file:
      - ./docker/config/redis.env
